version: "3.9"
services:
  habr:
    build: habrnewsimage/
    command: python ./requests_habr.py
    volumes:
      - storage:/storage/data

  ars:
    build: arsnewsimage/
    command: python ./requests_ars.py
    volumes:
      - storage:/storage/data

  web:
    build: webimage/
    command: python ./web.py
    volumes:
      - storage:/storage/data
    ports:
      - 8000:8000

volumes:
  storage: