version: "3.9"
services:
  web:
    build: webimage/
    command: python ./web.py
    ports:
      - 8000:8000

  habr:
    build: habrnewsimage/
    command: python ./requests_habr.py

  ars:
    build: arsnewsimage/
    command: python ./requests_ars.py